version: '3.8'

services:
  gstreamer-service:
    container_name: gstreamer-service
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - some_dummy_command_line_argument